config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('test_django.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

test_django/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

test_django/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

test_django/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

test_django/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

test_django/templates/base.html
{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}test_django{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'sass/app.scss' %}">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endcompress %}

    {% endblock %}

  </head>

  <body>

    <div class="title-bar" data-responsive-toggle="menu" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
      <div class="title-bar-title">Menu</div>
    </div>

    <div class="top-bar" id="menu">
      <div class="top-bar-left hide-for-small-only">
        <ul class="dropdown menu">
          <li class="menu-text">test_django</li>
        </ul>
      </div>

      <div class="top-bar-right">
        <ul class="vertical medium-horizontal menu">
          <li> <a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          {% if request.user.is_authenticated %}
            <li>
              {# URL provided by django-allauth/account/urls.py #}
              <a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
            </li>
            <li>
              {# URL provided by django-allauth/account/urls.py #}
              <a href="{% url 'account_logout' %}">{% trans "Sign out" %}</a>
            </li>
            {% else %}
            <li>
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
            </li>
            <li>
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>
            {% endif %}
        </ul>
      </div>

    </div>

    <div class="row">

      <div class="medium-6 medium-offset-3 columns">
        {% if messages %}
          {% for message in messages %}

            <div class="callout {% if message.tags %}{{ message.tags }}{% endif %}" data-closable>
            <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}</div>
          {% endfor %}
        {% endif %}
      </div>
    </div>

    {% block content %}
      <div class="row">
        <div class="medium-12 columns">
          <p>Use this document as a way to quick start any new project.</p>
        </div>
      </div>
    {% endblock content %}

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Foundation 6.2.3 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
      <script src="{% static 'libs/what-input/what-input.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

      <!-- Your stuff: Third-party javascript libraries go here -->

      <script>
        $(document).foundation();
      </script>
    {% endblock javascript %}
  </body>
</html>

test_django/templates/pages/about.html
{% extends "base.html" %}

test_django/templates/pages/home.html
{% extends "base.html" %}

test_django/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}

  <div class="row">
    <div class="small-12 columns">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="small-12 columns">
    <div class="button-group">
      <a class="button" href="{% url 'users:update' %}" role="button">My Info</a>
      <a class="button" href="{% url 'account_email' %}" role="button">E-Mail</a>
    </div>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

{% endblock content %}

test_django/templates/users/user_form.html
{% extends "base.html" %}
{% load foundation_formtags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <div class="row">
    <div class="medium-12 columns">
      <h1>{{ user.username }}</h1>
      <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
          {% csrf_token %}
          {{ form|as_foundation }}

          <button type="submit" class="button">Update</button>
          </div>
      </form>
    </div>
  </div>
{% endblock %}

test_django/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="row">

  <h2>Users</h2>

  <div>
    {% for user in user_list %}
      <div class="callout secondary">
        <a href="{% url 'users:detail' user.username %}" class="list-group-item">
          <h4 class="list-group-item-heading">{{ user.username }}</h4>
        </a>
      </div>
    {% endfor %}

  </div>

</div>
{% endblock content %}